import { db } from "./db";
import { users, policies, claims, payments } from "@shared/schema";
import bcrypt from "bcryptjs";

function requireDemoPassword() {
  const password = process.env.DEMO_PASSWORD || process.env.SEED_DEMO_PASSWORD || process.env.DEMO_SEED_PASSWORD || '';
  if (password.length < 12 || password.length > 1024) throw new Error('DEMO_PASSWORD must contain 12-1024 characters');
  return password;
}

export async function seedDatabase() {
  console.log("Seeding database...");

  // Hash password for all seed users
  const hashedPassword = await bcrypt.hash(requireDemoPassword(), 12);

  // ==========================================
  // SEED USERS (18 users with different roles)
  // ==========================================
  const seedUsers = [
    { id: "user-admin-1", email: "admin@safeguard.com", firstName: "Sarah", lastName: "Johnson", role: "admin", emailVerified: true, password: hashedPassword },
    { id: "user-admin-2", email: "admin2@safeguard.com", firstName: "Michael", lastName: "Chen", role: "admin", emailVerified: true, password: hashedPassword },
    { id: "user-agent-1", email: "agent1@safeguard.com", firstName: "Emily", lastName: "Rodriguez", role: "agent", emailVerified: true, password: hashedPassword },
    { id: "user-agent-2", email: "agent2@safeguard.com", firstName: "David", lastName: "Kim", role: "agent", emailVerified: true, password: hashedPassword },
    { id: "user-agent-3", email: "agent3@safeguard.com", firstName: "Lisa", lastName: "Thompson", role: "agent", emailVerified: true, password: hashedPassword },
    { id: "user-member-1", email: "john.doe@email.com", firstName: "John", lastName: "Doe", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-2", email: "jane.smith@email.com", firstName: "Jane", lastName: "Smith", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-3", email: "bob.wilson@email.com", firstName: "Bob", lastName: "Wilson", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-4", email: "alice.brown@email.com", firstName: "Alice", lastName: "Brown", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-5", email: "charlie.davis@email.com", firstName: "Charlie", lastName: "Davis", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-6", email: "diana.miller@email.com", firstName: "Diana", lastName: "Miller", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-7", email: "edward.garcia@email.com", firstName: "Edward", lastName: "Garcia", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-8", email: "fiona.martinez@email.com", firstName: "Fiona", lastName: "Martinez", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-9", email: "george.anderson@email.com", firstName: "George", lastName: "Anderson", role: "member", emailVerified: false, password: hashedPassword },
    { id: "user-member-10", email: "hannah.taylor@email.com", firstName: "Hannah", lastName: "Taylor", role: "member", emailVerified: false, password: hashedPassword },
    { id: "user-member-11", email: "ivan.thomas@email.com", firstName: "Ivan", lastName: "Thomas", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-12", email: "julia.jackson@email.com", firstName: "Julia", lastName: "Jackson", role: "member", emailVerified: true, password: hashedPassword },
    { id: "user-member-13", email: "kevin.white@email.com", firstName: "Kevin", lastName: "White", role: "member", emailVerified: false, password: hashedPassword },
  ];

  for (const u of seedUsers) {
    await db.insert(users).values(u).onConflictDoNothing();
  }
  console.log(`  Seeded ${seedUsers.length} users`);

  // ==========================================
  // SEED POLICIES (20 policies - mix of auto and home)
  // ==========================================
  const seedPolicies = [
    // Auto policies
    { userId: "user-member-1", type: "auto", status: "active", coverageAmount: "50000", monthlyPremium: "89.50", deductible: "1000", startDate: new Date("2024-01-15"), vehicleInfo: { make: "Toyota", model: "Camry", year: 2022, vin: "1HGBH41JXMN109186", mileage: 25000, primaryUse: "personal" } },
    { userId: "user-member-1", type: "home", status: "active", coverageAmount: "350000", monthlyPremium: "125.00", deductible: "2500", startDate: new Date("2024-02-01"), propertyInfo: { address: "123 Oak Street, Austin TX 78701", yearBuilt: 2005, squareFootage: 2200, propertyType: "single_family", constructionType: "frame", roofType: "shingle", hasSecuritySystem: true, hasFireAlarm: true } },
    { userId: "user-member-2", type: "auto", status: "active", coverageAmount: "75000", monthlyPremium: "112.00", deductible: "500", startDate: new Date("2024-03-10"), vehicleInfo: { make: "Honda", model: "Accord", year: 2023, vin: "2HGFA16598H523456", mileage: 12000, primaryUse: "personal" } },
    { userId: "user-member-2", type: "auto", status: "active", coverageAmount: "45000", monthlyPremium: "78.25", deductible: "1000", startDate: new Date("2024-04-05"), vehicleInfo: { make: "Ford", model: "Escape", year: 2021, vin: "3FAHP0HA1CR123456", mileage: 35000, primaryUse: "business" } },
    { userId: "user-member-3", type: "home", status: "active", coverageAmount: "500000", monthlyPremium: "195.75", deductible: "5000", startDate: new Date("2024-01-20"), propertyInfo: { address: "456 Maple Ave, Denver CO 80202", yearBuilt: 2015, squareFootage: 3500, propertyType: "single_family", constructionType: "masonry", roofType: "tile", hasSecuritySystem: true, hasFireAlarm: true } },
    { userId: "user-member-3", type: "auto", status: "suspended", coverageAmount: "30000", monthlyPremium: "65.00", deductible: "1000", startDate: new Date("2023-11-01"), vehicleInfo: { make: "Chevrolet", model: "Malibu", year: 2019, vin: "4T1BF1FK5CU123456", mileage: 55000, primaryUse: "personal" } },
    { userId: "user-member-4", type: "auto", status: "active", coverageAmount: "100000", monthlyPremium: "145.50", deductible: "500", startDate: new Date("2024-05-15"), vehicleInfo: { make: "Tesla", model: "Model 3", year: 2024, vin: "5YJ3E1EA8NF123456", mileage: 5000, primaryUse: "personal" } },
    { userId: "user-member-4", type: "home", status: "active", coverageAmount: "275000", monthlyPremium: "110.25", deductible: "2500", startDate: new Date("2024-06-01"), propertyInfo: { address: "789 Pine Rd, Portland OR 97201", yearBuilt: 1998, squareFootage: 1800, propertyType: "townhouse", constructionType: "frame", roofType: "shingle", hasSecuritySystem: false, hasFireAlarm: true } },
    { userId: "user-member-5", type: "auto", status: "active", coverageAmount: "60000", monthlyPremium: "95.00", deductible: "1000", startDate: new Date("2024-02-20"), vehicleInfo: { make: "BMW", model: "330i", year: 2022, vin: "WBA8B9G51JNU12345", mileage: 18000, primaryUse: "personal" } },
    { userId: "user-member-5", type: "home", status: "cancelled", coverageAmount: "200000", monthlyPremium: "85.50", deductible: "2500", startDate: new Date("2023-09-01"), endDate: new Date("2024-09-01"), propertyInfo: { address: "321 Elm St, Seattle WA 98101", yearBuilt: 1985, squareFootage: 1500, propertyType: "condo", constructionType: "concrete", roofType: "flat", hasSecuritySystem: true, hasFireAlarm: true } },
    { userId: "user-member-6", type: "auto", status: "active", coverageAmount: "40000", monthlyPremium: "72.00", deductible: "1500", startDate: new Date("2024-07-01"), vehicleInfo: { make: "Hyundai", model: "Tucson", year: 2023, vin: "KM8J3CA46NU123456", mileage: 8000, primaryUse: "personal" } },
    { userId: "user-member-7", type: "home", status: "active", coverageAmount: "425000", monthlyPremium: "168.00", deductible: "5000", startDate: new Date("2024-03-15"), propertyInfo: { address: "654 Cedar Blvd, Nashville TN 37201", yearBuilt: 2010, squareFootage: 2800, propertyType: "single_family", constructionType: "steel", roofType: "metal", hasSecuritySystem: true, hasFireAlarm: true } },
    { userId: "user-member-8", type: "auto", status: "active", coverageAmount: "55000", monthlyPremium: "88.75", deductible: "1000", startDate: new Date("2024-04-20"), vehicleInfo: { make: "Mazda", model: "CX-5", year: 2023, vin: "JM3KFBCM5N0123456", mileage: 15000, primaryUse: "pleasure" } },
    { userId: "user-member-8", type: "home", status: "active", coverageAmount: "315000", monthlyPremium: "138.50", deductible: "2500", startDate: new Date("2024-05-01"), propertyInfo: { address: "987 Birch Lane, Charlotte NC 28201", yearBuilt: 2018, squareFootage: 2400, propertyType: "single_family", constructionType: "frame", roofType: "shingle", hasSecuritySystem: true, hasFireAlarm: true } },
    { userId: "user-member-9", type: "auto", status: "active", coverageAmount: "35000", monthlyPremium: "62.50", deductible: "2000", startDate: new Date("2024-08-01"), vehicleInfo: { make: "Subaru", model: "Outback", year: 2021, vin: "4S4BSAFC5M3123456", mileage: 42000, primaryUse: "personal" } },
    { userId: "user-member-10", type: "auto", status: "active", coverageAmount: "80000", monthlyPremium: "118.00", deductible: "500", startDate: new Date("2024-06-15"), vehicleInfo: { make: "Audi", model: "A4", year: 2024, vin: "WAUFFAFL5EA123456", mileage: 3000, primaryUse: "personal" } },
    { userId: "user-member-11", type: "home", status: "active", coverageAmount: "600000", monthlyPremium: "225.00", deductible: "5000", startDate: new Date("2024-01-01"), propertyInfo: { address: "159 Walnut Dr, San Francisco CA 94101", yearBuilt: 2020, squareFootage: 4000, propertyType: "single_family", constructionType: "concrete", roofType: "tile", hasSecuritySystem: true, hasFireAlarm: true } },
    { userId: "user-member-12", type: "auto", status: "suspended", coverageAmount: "25000", monthlyPremium: "55.00", deductible: "2000", startDate: new Date("2023-12-01"), vehicleInfo: { make: "Nissan", model: "Altima", year: 2018, vin: "1N4AL3AP4JC123456", mileage: 72000, primaryUse: "business" } },
    { userId: "user-member-12", type: "home", status: "active", coverageAmount: "180000", monthlyPremium: "78.25", deductible: "2500", startDate: new Date("2024-09-01"), propertyInfo: { address: "753 Spruce Ct, Phoenix AZ 85001", yearBuilt: 1992, squareFootage: 1400, propertyType: "condo", constructionType: "masonry", roofType: "flat", hasSecuritySystem: false, hasFireAlarm: true } },
    { userId: "user-member-13", type: "auto", status: "active", coverageAmount: "65000", monthlyPremium: "98.50", deductible: "1000", startDate: new Date("2024-10-01"), vehicleInfo: { make: "Volkswagen", model: "Tiguan", year: 2023, vin: "3VV2B7AX5NM123456", mileage: 9500, primaryUse: "personal" } },
  ];

  for (const p of seedPolicies) {
    await db.insert(policies).values(p as any).onConflictDoNothing();
  }
  console.log(`  Seeded ${seedPolicies.length} policies`);

  // ==========================================
  // SEED CLAIMS (20 claims with different statuses)
  // ==========================================
  const seedClaims = [
    { userId: "user-member-1", policyId: 1, title: "Rear bumper collision damage", description: "Hit from behind at a stoplight. Rear bumper cracked, tail lights broken, trunk dented.", status: "submitted", estimatedAmount: "3500", incidentDate: new Date("2024-11-15"), images: [], aiAssessment: { damageType: "Collision", severity: "moderate", affectedComponents: ["rear bumper", "tail lights", "trunk"], repairComplexity: "moderate", estimatedCost: { parts: 1500, labor: 2000, total: 3500 }, confidence: 0.85, description: "Moderate rear-end collision damage", recommendations: ["Replace rear bumper", "Replace tail light assembly", "Repair trunk dent"] } },
    { userId: "user-member-1", policyId: 2, title: "Storm damage to roof shingles", description: "Heavy hailstorm caused multiple roof shingle cracks and water leak in attic.", status: "processing", estimatedAmount: "8500", incidentDate: new Date("2024-10-20"), images: [], aiAssessment: { damageType: "Weather", severity: "major", affectedComponents: ["roof shingles", "attic insulation", "gutters"], repairComplexity: "complex", estimatedCost: { parts: 4000, labor: 4500, total: 8500 }, confidence: 0.78, description: "Significant hail damage to roof", recommendations: ["Replace damaged shingles", "Repair attic insulation", "Clean and repair gutters"] } },
    { userId: "user-member-2", policyId: 3, title: "Windshield crack from debris", description: "Rock hit windshield on highway, large crack spanning full width.", status: "approved", estimatedAmount: "800", approvedAmount: "750", incidentDate: new Date("2024-12-01"), images: [], aiAssessment: { damageType: "Impact", severity: "minor", affectedComponents: ["windshield"], repairComplexity: "simple", estimatedCost: { parts: 500, labor: 300, total: 800 }, confidence: 0.92, description: "Windshield replacement needed", recommendations: ["Full windshield replacement"] } },
    { userId: "user-member-2", policyId: 4, title: "Side mirror knocked off in parking lot", description: "Someone sideswiped the car in parking lot. Driver side mirror completely gone.", status: "paid", estimatedAmount: "450", approvedAmount: "400", paidAmount: "400", incidentDate: new Date("2024-09-25"), images: [], aiAssessment: { damageType: "Collision", severity: "minor", affectedComponents: ["driver side mirror", "door paint"], repairComplexity: "simple", estimatedCost: { parts: 250, labor: 200, total: 450 }, confidence: 0.9, description: "Side mirror replacement with minor paint touch-up", recommendations: ["Replace mirror assembly", "Touch up door paint"] } },
    { userId: "user-member-3", policyId: 5, title: "Burst pipe flooding in basement", description: "Pipe burst during cold snap, flooding basement and damaging drywall and flooring.", status: "processing", estimatedAmount: "12000", incidentDate: new Date("2024-12-10"), images: [], aiAssessment: { damageType: "Water", severity: "major", affectedComponents: ["basement drywall", "flooring", "electrical", "plumbing"], repairComplexity: "complex", estimatedCost: { parts: 5000, labor: 7000, total: 12000 }, confidence: 0.75, description: "Extensive water damage from burst pipe", recommendations: ["Water extraction", "Replace drywall", "Replace flooring", "Electrical inspection", "Pipe repair"] } },
    { userId: "user-member-3", policyId: 6, title: "Fender bender at intersection", description: "Low speed collision at intersection. Front bumper and headlight damaged.", status: "denied", estimatedAmount: "2200", incidentDate: new Date("2024-08-15"), images: [], aiAssessment: { damageType: "Collision", severity: "moderate", affectedComponents: ["front bumper", "headlight", "hood"], repairComplexity: "moderate", estimatedCost: { parts: 1000, labor: 1200, total: 2200 }, confidence: 0.82, description: "Front-end collision damage", recommendations: ["Replace front bumper", "Replace headlight assembly", "Inspect hood alignment"] } },
    { userId: "user-member-4", policyId: 7, title: "Vandalism scratches on Tesla", description: "Someone keyed both sides of the car in a parking garage. Deep scratches.", status: "submitted", estimatedAmount: "4800", incidentDate: new Date("2025-01-05"), images: [], aiAssessment: { damageType: "Vandalism", severity: "moderate", affectedComponents: ["driver side panels", "passenger side panels", "doors"], repairComplexity: "moderate", estimatedCost: { parts: 1800, labor: 3000, total: 4800 }, confidence: 0.88, description: "Extensive keying damage on both sides", recommendations: ["Sand and repaint affected panels", "Clear coat application"] } },
    { userId: "user-member-4", policyId: 8, title: "Tree fell on garage during storm", description: "Large oak tree fell during windstorm, crushing garage roof and damaging one wall.", status: "approved", estimatedAmount: "18000", approvedAmount: "16500", incidentDate: new Date("2024-11-28"), images: [], aiAssessment: { damageType: "Weather", severity: "total", affectedComponents: ["garage roof", "garage wall", "garage door", "structural beams"], repairComplexity: "complex", estimatedCost: { parts: 8000, labor: 10000, total: 18000 }, confidence: 0.72, description: "Major structural damage from fallen tree", recommendations: ["Tree removal", "Roof replacement", "Wall reconstruction", "Structural inspection"] } },
    { userId: "user-member-5", policyId: 9, title: "Deer collision on rural road", description: "Hit a deer at dusk on country road. Hood crumpled, radiator damaged, airbags deployed.", status: "processing", estimatedAmount: "7500", incidentDate: new Date("2024-12-20"), images: [], aiAssessment: { damageType: "Collision", severity: "major", affectedComponents: ["hood", "radiator", "grille", "airbags", "bumper"], repairComplexity: "complex", estimatedCost: { parts: 3500, labor: 4000, total: 7500 }, confidence: 0.8, description: "Major front-end damage from animal collision", recommendations: ["Replace hood", "Replace radiator", "Replace grille", "Airbag replacement", "Frame inspection"] } },
    { userId: "user-member-6", policyId: 11, title: "Minor parking lot scrape", description: "Scraped against a pillar in parking garage. Paint damage on passenger side.", status: "submitted", estimatedAmount: "900", incidentDate: new Date("2025-01-10"), images: [], aiAssessment: { damageType: "Collision", severity: "minor", affectedComponents: ["passenger door", "rear quarter panel"], repairComplexity: "simple", estimatedCost: { parts: 300, labor: 600, total: 900 }, confidence: 0.91, description: "Minor paint scrape damage", recommendations: ["Sand and repaint affected area", "Apply clear coat"] } },
    { userId: "user-member-7", policyId: 12, title: "Kitchen fire smoke damage", description: "Grease fire in kitchen. Fire contained but smoke damage throughout first floor.", status: "approved", estimatedAmount: "15000", approvedAmount: "14000", incidentDate: new Date("2024-10-05"), images: [], aiAssessment: { damageType: "Fire", severity: "major", affectedComponents: ["kitchen cabinets", "walls", "ceiling", "flooring", "appliances"], repairComplexity: "complex", estimatedCost: { parts: 7000, labor: 8000, total: 15000 }, confidence: 0.76, description: "Smoke and minor fire damage in kitchen area", recommendations: ["Replace kitchen cabinets", "Repaint walls and ceiling", "Deep clean/replace flooring", "Replace damaged appliances"] } },
    { userId: "user-member-8", policyId: 13, title: "Hail damage on car hood and roof", description: "Golf ball sized hail dented the hood, roof, and trunk of the car.", status: "paid", estimatedAmount: "5200", approvedAmount: "5000", paidAmount: "5000", incidentDate: new Date("2024-07-15"), images: [], aiAssessment: { damageType: "Weather", severity: "moderate", affectedComponents: ["hood", "roof", "trunk", "paint"], repairComplexity: "moderate", estimatedCost: { parts: 2000, labor: 3200, total: 5200 }, confidence: 0.86, description: "Multiple hail dents across vehicle body", recommendations: ["Paintless dent repair", "Touch up paint where needed"] } },
    { userId: "user-member-8", policyId: 14, title: "Window broken by burglary attempt", description: "Someone tried to break in through the front window. Glass shattered, frame damaged.", status: "submitted", estimatedAmount: "2800", incidentDate: new Date("2025-01-15"), images: [], aiAssessment: { damageType: "Vandalism", severity: "moderate", affectedComponents: ["front window", "window frame", "interior wall"], repairComplexity: "moderate", estimatedCost: { parts: 1200, labor: 1600, total: 2800 }, confidence: 0.83, description: "Forced entry damage to window area", recommendations: ["Replace window glass", "Repair window frame", "Patch interior wall damage", "Consider security upgrade"] } },
    { userId: "user-member-9", policyId: 15, title: "Rear-end collision at highway merge", description: "Rear-ended while merging onto highway. Trunk crushed, rear lights destroyed.", status: "processing", estimatedAmount: "6000", incidentDate: new Date("2024-12-28"), images: [], aiAssessment: { damageType: "Collision", severity: "major", affectedComponents: ["trunk", "rear bumper", "tail lights", "rear quarter panels"], repairComplexity: "complex", estimatedCost: { parts: 2800, labor: 3200, total: 6000 }, confidence: 0.81, description: "Significant rear-end damage", recommendations: ["Replace trunk lid", "Replace rear bumper", "Replace tail light assemblies", "Frame alignment check"] } },
    { userId: "user-member-10", policyId: 16, title: "Road debris tire and rim damage", description: "Hit large debris on highway. Two tires blown out, rims bent, alignment off.", status: "approved", estimatedAmount: "3200", approvedAmount: "3000", incidentDate: new Date("2024-11-05"), images: [], aiAssessment: { damageType: "Impact", severity: "moderate", affectedComponents: ["front tires", "rims", "suspension"], repairComplexity: "moderate", estimatedCost: { parts: 2000, labor: 1200, total: 3200 }, confidence: 0.87, description: "Tire and rim damage from road debris", recommendations: ["Replace two tires", "Replace bent rims", "Alignment service", "Suspension inspection"] } },
    { userId: "user-member-11", policyId: 17, title: "Earthquake crack in foundation", description: "Recent earthquake caused visible crack in home foundation and shifted door frames.", status: "submitted", estimatedAmount: "25000", incidentDate: new Date("2025-01-20"), images: [], aiAssessment: { damageType: "Natural disaster", severity: "major", affectedComponents: ["foundation", "door frames", "walls", "driveway"], repairComplexity: "complex", estimatedCost: { parts: 10000, labor: 15000, total: 25000 }, confidence: 0.7, description: "Earthquake structural damage", recommendations: ["Foundation repair", "Realign door frames", "Repair wall cracks", "Structural engineering assessment"] } },
    { userId: "user-member-12", policyId: 18, title: "Catalytic converter theft", description: "Catalytic converter stolen from car overnight. Cut clean off the exhaust system.", status: "paid", estimatedAmount: "2500", approvedAmount: "2300", paidAmount: "2300", incidentDate: new Date("2024-10-30"), images: [], aiAssessment: { damageType: "Theft", severity: "moderate", affectedComponents: ["catalytic converter", "exhaust pipe", "heat shields"], repairComplexity: "moderate", estimatedCost: { parts: 1800, labor: 700, total: 2500 }, confidence: 0.93, description: "Catalytic converter theft and exhaust damage", recommendations: ["Replace catalytic converter", "Repair exhaust pipe", "Install anti-theft shield"] } },
    { userId: "user-member-12", policyId: 19, title: "Water heater leak damage", description: "Water heater burst, flooding utility room and adjacent bedroom carpet.", status: "processing", estimatedAmount: "4500", incidentDate: new Date("2025-01-08"), images: [], aiAssessment: { damageType: "Water", severity: "moderate", affectedComponents: ["utility room floor", "bedroom carpet", "drywall", "baseboards"], repairComplexity: "moderate", estimatedCost: { parts: 2000, labor: 2500, total: 4500 }, confidence: 0.8, description: "Water damage from failed water heater", recommendations: ["Replace water heater", "Replace carpet", "Repair drywall", "Mold inspection"] } },
    { userId: "user-member-13", policyId: 20, title: "Hit and run door dent", description: "Someone hit the driver door in a parking lot and drove away. Large dent and paint damage.", status: "submitted", estimatedAmount: "1800", incidentDate: new Date("2025-02-01"), images: [], aiAssessment: { damageType: "Collision", severity: "minor", affectedComponents: ["driver door", "paint"], repairComplexity: "moderate", estimatedCost: { parts: 700, labor: 1100, total: 1800 }, confidence: 0.89, description: "Hit and run door damage", recommendations: ["Repair door dent", "Repaint door panel"] } },
  ];

  for (const c of seedClaims) {
    await db.insert(claims).values(c as any).onConflictDoNothing();
  }
  console.log(`  Seeded ${seedClaims.length} claims`);

  // ==========================================
  // SEED PAYMENTS (20 payments with different statuses and methods)
  // ==========================================
  const seedPayments = [
    { userId: "user-member-1", policyId: 1, type: "premium", amount: "89.50", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-02-01") },
    { userId: "user-member-1", policyId: 1, type: "premium", amount: "89.50", currency: "USD", paymentMethod: "bitcoin", bitcoinAddress: "tb1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh", bitcoinAmount: "0.00198889", status: "confirmed", createdAt: new Date("2024-03-01") },
    { userId: "user-member-1", policyId: 2, type: "premium", amount: "125.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-03-01") },
    { userId: "user-member-2", policyId: 3, type: "premium", amount: "112.00", currency: "USD", paymentMethod: "bitcoin", bitcoinAddress: "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx", bitcoinAmount: "0.00248889", status: "confirmed", createdAt: new Date("2024-04-01") },
    { userId: "user-member-2", policyId: 3, type: "premium", amount: "112.00", currency: "USD", paymentMethod: "traditional", status: "pending", createdAt: new Date("2024-05-01") },
    { userId: "user-member-2", claimId: 4, type: "claim_payout", amount: "400.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-10-15") },
    { userId: "user-member-3", policyId: 5, type: "premium", amount: "195.75", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-02-01") },
    { userId: "user-member-3", policyId: 5, type: "premium", amount: "195.75", currency: "USD", paymentMethod: "bitcoin", bitcoinAddress: "tb1qrp33g0q5b5698ahp5jnf5yzjmgcel8tkculhmg", bitcoinAmount: "0.00435000", status: "pending", createdAt: new Date("2024-03-01") },
    { userId: "user-member-4", policyId: 7, type: "premium", amount: "145.50", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-06-01") },
    { userId: "user-member-4", policyId: 8, type: "premium", amount: "110.25", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-07-01") },
    { userId: "user-member-4", claimId: 8, type: "claim_payout", amount: "16500.00", currency: "USD", paymentMethod: "traditional", status: "pending", createdAt: new Date("2024-12-20") },
    { userId: "user-member-5", policyId: 9, type: "premium", amount: "95.00", currency: "USD", paymentMethod: "bitcoin", bitcoinAddress: "tb1q0sg9rdst255gtldsmcf8rk0764avqy2h2rl9t4", bitcoinAmount: "0.00211111", status: "confirmed", createdAt: new Date("2024-03-01") },
    { userId: "user-member-6", policyId: 11, type: "premium", amount: "72.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-08-01") },
    { userId: "user-member-7", policyId: 12, type: "premium", amount: "168.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-04-01") },
    { userId: "user-member-7", claimId: 11, type: "claim_payout", amount: "14000.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-11-15") },
    { userId: "user-member-8", policyId: 13, type: "premium", amount: "88.75", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-05-01") },
    { userId: "user-member-8", claimId: 12, type: "claim_payout", amount: "5000.00", currency: "USD", paymentMethod: "bitcoin", bitcoinAddress: "tb1qm34lsc65zpw79lxes69zkqmk6ee3ewf0j77s3h", bitcoinAmount: "0.11111111", status: "confirmed", createdAt: new Date("2024-08-20") },
    { userId: "user-member-9", policyId: 15, type: "premium", amount: "62.50", currency: "USD", paymentMethod: "traditional", status: "failed", createdAt: new Date("2024-09-01") },
    { userId: "user-member-10", policyId: 16, type: "premium", amount: "118.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-07-01") },
    { userId: "user-member-12", claimId: 17, type: "claim_payout", amount: "2300.00", currency: "USD", paymentMethod: "traditional", status: "confirmed", createdAt: new Date("2024-11-30") },
  ];

  for (const p of seedPayments) {
    await db.insert(payments).values(p as any).onConflictDoNothing();
  }
  console.log(`  Seeded ${seedPayments.length} payments`);

  console.log("Database seeding complete!");
}
